#!/usr/bin/env python3
import json, math, time, urllib.parse, urllib.request
from collections import Counter
from pathlib import Path
ENDPOINT='https://www.stoloto.ru/p/api/mobile/api/v35/service/draws/archive'
HEADERS={'accept':'*/*','device-platform':'DESKTOP','device-type':'STOLOTO','gosloto-partner':'bXMjXFRXZ3coWXh6R3s1NTdUX3dnWlBMLUxmdg','referer':'https://www.stoloto.ru/oxota/archive','user-agent':'Mozilla/5.0 LotoOS-Ohota-Control/1.1'}
P0=[0.375644995,0.462332301,0.148606811,0.013209494,0.000206398]
Q=[0.553487068,0.376364933,0.066837266,0.003282397,0.000028336]
OUT=Path('.research-sportloto/out');OUT.mkdir(parents=True,exist_ok=True)
def fetch(page):
 u=ENDPOINT+'?'+urllib.parse.urlencode({'game':'oxota','count':50,'page':page})
 req=urllib.request.Request(u,headers=HEADERS)
 for a in range(4):
  try:
   with urllib.request.urlopen(req,timeout=20) as r:return json.load(r)
  except Exception:
   if a==3:raise
   time.sleep(1+a)
def norm(d):
 if d.get('status')!='COMPLETED' or d.get('completed') is False:return None
 s=((d.get('combination') or {}).get('structured'))
 if not isinstance(s,list) or len(s)!=8:return None
 z=[int(x) for x in s];a=z[:4];b=z[4:]
 if any(len(set(f))!=4 or any(x<1 or x>20 for x in f) for f in (a,b)):return None
 return {'number':int(d['number']),'date':d['date'],'A':a,'B':b,'K':len(set(a)&set(b))}
by={};bad=0;pages=0
for page in range(1,101):
 x=fetch(page);raw=x.get('draws',[])
 if x.get('requestStatus')!='success' or not isinstance(raw,list):raise SystemExit('schema mismatch')
 for d in raw:
  r=norm(d)
  if r:by[r['number']]=r
  else:bad+=1
 pages+=1
 if len(raw)<50 or not x.get('hasMore',False):break
rows=[by[n] for n in sorted(by)]
if len(rows)<1000:raise SystemExit(f'too few valid rows: {len(rows)}, bad={bad}')
n=len(rows);c=[0]*5
for r in rows:c[r['K']]+=1
mu0=sum(k*P0[k] for k in range(5));mean=sum(k*c[k] for k in range(5))/n
var0=sum((k-mu0)**2*P0[k] for k in range(5));z=(mean-mu0)/math.sqrt(var0/n)
lr=sum(c[k]*math.log(Q[k]/P0[k]) for k in range(5))
pear=sum((c[k]-n*P0[k])**2/(n*P0[k]) for k in range(5))
g2=2*sum(c[k]*math.log(c[k]/(n*P0[k])) for k in range(5) if c[k])
bd=0.0
for k in range(5):
 bq=sum((Q[j]-(1 if j==k else 0))**2 for j in range(5));b0=sum((P0[j]-(1 if j==k else 0))**2 for j in range(5))
 bd+=c[k]*(bq-b0)
bd/=n
quart=[]
for j in range(4):
 a=j*n//4;b=(j+1)*n//4;rr=rows[a:b];cc=Counter(r['K'] for r in rr);nn=len(rr)
 ll=sum(cc[k]*math.log(Q[k]/P0[k]) for k in range(5));mm=sum(k*cc[k] for k in range(5))/nn
 quart.append({'part':j+1,'n':nn,'first':rr[0]['number'],'last':rr[-1]['number'],'firstDate':rr[0]['date'],'lastDate':rr[-1]['date'],'counts':[cc[k] for k in range(5)],'meanK':mm,'fixedQ_logLR':ll,'fixedQ_E':math.exp(ll) if ll>-745 else 0.0})
rep={'source':'official Stoloto API','lottery':'Охота','gameSlug':'oxota','pages':pages,'n':n,'invalidRows':bad,'first':rows[0]['number'],'firstDate':rows[0]['date'],'last':rows[-1]['number'],'lastDate':rows[-1]['date'],'counts':c,'meanK':mean,'iidMean':mu0,'meanZ':z,'pearson':pear,'g2':g2,'frozenQ_logLR_vs_IID':lr,'frozenQ_E':math.exp(lr) if lr>-745 else 0.0,'meanBrierDiff_q_minus_IID':bd,'quartiles':quart,'scope':'Independent same-formula GSC control. Official Ohota page states draws are generated by GSC every 15 minutes. This does not establish that the exact same physical RNG unit/software version is used for Sportloto 4x20.'}
json.dump(rep,open(OUT/'ohota-recent-control.json','w',encoding='utf-8'),ensure_ascii=False,indent=2)
with open(OUT/'ohota-recent-k.csv','w',encoding='utf-8') as f:
 f.write('draw_id,date,K\n')
 for r in rows:f.write(f"{r['number']},{r['date']},{r['K']}\n")
print(json.dumps(rep,ensure_ascii=False))
